version: 2
jobs:
  build:
    docker:
      - image: node:10.15.3-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run: npx aws s3 sync public/ s3://nikmouz.dev --delete
