version: 2
jobs:
  build:
    docker:
      - image: cypress/base:10.15.3
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - restore_cache:
          keys:
            - v2-cypress-binary
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - save_cache:
          paths:
            - /root/.cache/Cypress/**
          key: v2-cypress-binary
      - run: yarn build
      - run: yarn serve & yarn wait && yarn test
      - run: apt install -y python-pip
      - run: pip -q install awscli
      - run: aws s3 sync public/ s3://nikmouz.dev --delete
