version: 2
jobs:
  build:
    docker:
      - image: cypress/base:10.15.3
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            - v3-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run: yarn run cypress install
      - run: yarn serve & yarn wait && yarn test
      - run: apt install -y python-pip
      - run: pip -q install awscli
      - run: aws s3 sync --delete --no-progress public/ s3://nikmouz.dev
