version: 2
jobs:
  build:
    docker:
      - image: node:10.15.3-stretch
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run: apt-get update && apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb
      - run: yarn serve & yarn wait && yarn test
      - run: apt install -y python-pip
      - run: pip -q install awscli
      - run: aws s3 sync public/ s3://nikmouz.dev --delete
