version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - npm run test:ci
      - aws s3 sync --delete --no-progress public/ s3://nikmouz.dev
artifacts:
  files:
    - reports/**/*
  name: reports_$(date +%Y-%m-%d_%H:%M:%S)
cache:
  paths:
    - node_modules/**/*
