version: 0.2
phases:
  install:
    commands:
      - apt update && apt install -y python-pip
      - pip -q install awscli
      - yarn install
      - yarn run cypress install
  build:
    commands:
      - yarn build
      - yarn serve & yarn wait && yarn test
      - aws s3 sync --delete --no-progress public/ s3://nikmouz.dev
artifacts:
  files:
    - cypress/videos/*
  name: test-videos-$(date +%Y-%m-%d)
cache:
  paths:
    - node_modules/**/*
