version: 0.2
phases:
  install:
    commands:
      - yarn install
  build:
    commands:
      - yarn build
      - yarn test:ci
      - aws s3 sync --delete --no-progress public/ s3://nikmouz.dev
artifacts:
  files:
    - screenshots/**/*
  name: test-screenshots-$(date +%Y-%m-%d %H:%M:%S %s)
cache:
  paths:
    - node_modules/**/*
