# Based off this template:
# https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/services/S3/S3_Website_With_CloudFront_Distribution.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Website infrastructure template for nikmouz.dev'
Parameters:
  HostedZone:
    Type: String
    Default: 'nikmouz.dev'
    Description: The DNS name of an existing Amazon Route 53 hosted zone
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
  Certificate:
    Type: String
    Default: 'arn:aws:acm:eu-west-1:005405328181:certificate/c346f805-c3aa-462b-a483-909112c10d64'
    Description: The Acm Certificate Arn value

Resources:
  WebsiteS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref 'HostedZone'
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteS3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: s3:GetObject
            Resource: !Sub '${WebsiteS3Bucket.Arn}/*'
            Principal: '*'

  WebsiteLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['', [!Ref 'HostedZone', '-logs']]
      AccessControl: BucketOwnerFullControl

  WebsiteCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref 'HostedZone'
          - !Join ['', ['www', ., !Ref 'HostedZone']]
        Enabled: 'true'
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: 'true'
          TargetOriginId: only-origin
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        Logging:
          Bucket: !GetAtt [WebsiteLogsBucket, DomainName]
          IncludeCookies: 'true'
          Prefix: !Ref 'HostedZone'
        Origins:
          - CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: http-only
            DomainName: !Join ['', [!Ref 'WebsiteS3Bucket', '.s3-website-eu-west-1.amazonaws.com']]
            Id: only-origin
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref 'Certificate'
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: WebsiteRedirectLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - logs:*
                Resource: arn:aws:logs:*:*:*
                Effect: Allow

  WebsiteRedirectLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: redirect-www-to-naked
      Description: Redirect www subdomain to naked
      Runtime: nodejs8.10
      Role: !GetAtt 'LambdaRole.Arn'
      Handler: index.handler
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            console.log("Event:", JSON.stringify(event));

            // Removes www subdomain from host
            const host = event.headers.Host.replace(new RegExp("^www\."), "");

            const location = `https://${host}${event.path}`;
            console.log("Redirecting to: " + location);

            const response = {
            statusCode: 301,
            headers: { location, "content-type": "text/html" }
            };

            return response;
          };

  WebsiteRecordSets:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Join ['', [!Ref 'HostedZone', .]]
      RecordSets:
        - Name: !Ref 'HostedZone'
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt [WebsiteCDN, DomainName]
        - Name: !Join ['', ['www', ., !Ref 'HostedZone']]
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt [WebsiteCDN, DomainName]

Outputs:
  WebsiteURL:
    Value: !Join ['', ['https://', 'www', ., !Ref 'HostedZone']]
    Description: nikmouz website URL
  S3EndpointURL:
    Value: !Join ['', [!Ref 'WebsiteS3Bucket', '.s3-website.eu-west-1.amazonaws.com']]
    Description: S3 Endpoint
  CloudFrontEndpointURL:
    Value: !GetAtt [WebsiteCDN, DomainName]
    Description: CloudFront Endpoint